package projetofinal;
import Dados.centroDeAdoção;
import Dados.Usuarios;
import Banco.CentroAdoçãoBD;
import Banco.Conexao;
import Banco.DoadoresBD;
import Dados.Doadores;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import Dados.centroDeAdoção;
import Banco.CentroAdoçãoBD;
import Dados.CadastroPets;
import java.sql.PreparedStatement;

/**
 *
 * @author aluno
 */
public class TelaPrincipalCentroAdoção extends javax.swing.JFrame {

    public TelaCadastroPets TelaCadastroPets;
    private centroDeAdoção centroDeAdoção;
    private CentroAdoçãoBD CentroAdoçãoBD;
    private AlterarCadastroCentro AlterarCadastroCentro;
    private campoOutraEspecie campoOutraEspecie;
    private telaEspeciePet telaEspeciePet;
    private ExcluirPets ExcluirPets;
    private TelaLogin TelaLogin;
    private ExcluirPetsDoadores ExcluirPetsDoadores;
    private String contato, centro;
    
    
     Connection connection = Conexao.getInstance().getConnection();
    
    
    
    public TelaPrincipalCentroAdoção() {
        initComponents();
        
        TelaCadastroPets = new TelaCadastroPets();
        centroDeAdoção = new centroDeAdoção();
        CentroAdoçãoBD = new CentroAdoçãoBD();
        AlterarCadastroCentro = new AlterarCadastroCentro();
        campoOutraEspecie = new campoOutraEspecie();
        telaEspeciePet = new telaEspeciePet();
        ExcluirPets = new ExcluirPets();
        ExcluirPetsDoadores = new ExcluirPetsDoadores();
        
        
    }
    public void setEmailText(String email) {
        TxtEmailPerfil.setText(email);
    }
    public void setNomeFantasiaText(String nome) {
        TxtNomePerfil.setText(nome);
    }
    public void setCnpjText (String cnpj){
        TxtCnpjPerfil.setText(cnpj);
    }
    public void setEnderecoText(String endereco){
        TxtEndereçoPerfil.setText(endereco);
    }
    public void setCelularText(String celular){
        TxtCelularPerfil.setText(celular);
    }
    public void setInstagramText(String instagram){
        TxtInstagramPerfil.setText(instagram);
        
    }
    public String getContato(){
        return contato;
    }
    public String getCentro(){
        return centro;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NomePerfil = new javax.swing.JLabel();
        TxtNomePerfil = new javax.swing.JTextField();
        CnpjPerfil = new javax.swing.JLabel();
        TxtCnpjPerfil = new javax.swing.JTextField();
        endereçoPerfil = new javax.swing.JLabel();
        TxtEndereçoPerfil = new javax.swing.JTextField();
        endereçoPerfil1 = new javax.swing.JLabel();
        TxtCelularPerfil = new javax.swing.JTextField();
        instagramPerfil = new javax.swing.JLabel();
        TxtInstagramPerfil = new javax.swing.JTextField();
        emailPerfil = new javax.swing.JLabel();
        TxtEmailPerfil = new javax.swing.JTextField();
        BotaoCadastrarPets = new javax.swing.JButton();
        BotaoAlterarDados = new javax.swing.JButton();
        BotaoSairPerfil = new javax.swing.JButton();
        BotaoExcluirPerfil = new javax.swing.JButton();
        BotaoCadastrarPets1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perfil Centro de Adoção");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(77, 255, 148));
        jPanel1.setForeground(new java.awt.Color(77, 255, 148));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);

        NomePerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NomePerfil.setText("Nome Fantasia");

        TxtNomePerfil.setEditable(false);
        TxtNomePerfil.setBackground(new java.awt.Color(204, 204, 204));
        TxtNomePerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtNomePerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomePerfilActionPerformed(evt);
            }
        });

        CnpjPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CnpjPerfil.setText("CNPJ");

        TxtCnpjPerfil.setEditable(false);
        TxtCnpjPerfil.setBackground(new java.awt.Color(204, 204, 204));
        TxtCnpjPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        endereçoPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        endereçoPerfil.setText("Endereço");

        TxtEndereçoPerfil.setEditable(false);
        TxtEndereçoPerfil.setBackground(new java.awt.Color(204, 204, 204));
        TxtEndereçoPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtEndereçoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEndereçoPerfilActionPerformed(evt);
            }
        });

        endereçoPerfil1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        endereçoPerfil1.setText("Celular");

        TxtCelularPerfil.setEditable(false);
        TxtCelularPerfil.setBackground(new java.awt.Color(204, 204, 204));
        TxtCelularPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtCelularPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCelularPerfilActionPerformed(evt);
            }
        });

        instagramPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        instagramPerfil.setText("Instagram");

        TxtInstagramPerfil.setEditable(false);
        TxtInstagramPerfil.setBackground(new java.awt.Color(204, 204, 204));
        TxtInstagramPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        emailPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailPerfil.setText("Email");

        TxtEmailPerfil.setEditable(false);
        TxtEmailPerfil.setBackground(new java.awt.Color(204, 204, 204));
        TxtEmailPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtEmailPerfil.setSelectionColor(new java.awt.Color(0, 0, 0));
        TxtEmailPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailPerfilActionPerformed(evt);
            }
        });

        BotaoCadastrarPets.setBackground(new java.awt.Color(77, 255, 148));
        BotaoCadastrarPets.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotaoCadastrarPets.setText("Cadastrar Pets");
        BotaoCadastrarPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarPetsActionPerformed(evt);
            }
        });

        BotaoAlterarDados.setBackground(new java.awt.Color(77, 255, 148));
        BotaoAlterarDados.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotaoAlterarDados.setText("Alterar Dados");
        BotaoAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarDadosActionPerformed(evt);
            }
        });

        BotaoSairPerfil.setBackground(new java.awt.Color(77, 255, 148));
        BotaoSairPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotaoSairPerfil.setText("Sair");
        BotaoSairPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairPerfilActionPerformed(evt);
            }
        });

        BotaoExcluirPerfil.setBackground(new java.awt.Color(77, 255, 148));
        BotaoExcluirPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotaoExcluirPerfil.setText("Excluir conta");
        BotaoExcluirPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirPerfilActionPerformed(evt);
            }
        });

        BotaoCadastrarPets1.setBackground(new java.awt.Color(77, 255, 148));
        BotaoCadastrarPets1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotaoCadastrarPets1.setText("Excluir Pets");
        BotaoCadastrarPets1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarPets1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomePerfil)
                    .addComponent(instagramPerfil)
                    .addComponent(TxtInstagramPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CnpjPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtCnpjPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCelularPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endereçoPerfil1)
                            .addComponent(TxtEmailPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailPerfil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoCadastrarPets1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(BotaoAlterarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BotaoSairPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotaoExcluirPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotaoCadastrarPets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(24, 24, 24)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endereçoPerfil)
                            .addComponent(TxtEndereçoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomePerfil)
                    .addComponent(endereçoPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEndereçoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CnpjPerfil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BotaoCadastrarPets)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(endereçoPerfil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtCnpjPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoAlterarDados)
                            .addComponent(TxtCelularPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BotaoCadastrarPets1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoExcluirPerfil)
                            .addComponent(emailPerfil)
                            .addComponent(instagramPerfil))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtInstagramPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoSairPerfil)
                            .addComponent(TxtEmailPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Perfil Centro de Adoção");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairPerfilActionPerformed
        TelaLogin = new TelaLogin();
        TelaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoSairPerfilActionPerformed

    private void BotaoAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarDadosActionPerformed
        try 
        {
            String usuario;
        
            usuario = TxtNomePerfil.getText();
            
            
            centroDeAdoção objDoador = new centroDeAdoção();
            objDoador.setNomeFantasia(usuario);
            
            
            CentroAdoçãoBD objDoadorBD = new CentroAdoçãoBD();
            ResultSet resul = objDoadorBD.PedirDadosCentros(objDoador);
            
            if (resul.next()) 
            {
                
                String emailAutenticado = resul.getString("Email");
                String nome = resul.getString("NomeFantasia");
                String cnpj = resul.getString("CNPJ");
                String endereco = resul.getString("Endereco");
                String celular = resul.getString("Celular");
                String senha = resul.getString("Senha");
                int id = resul.getInt("ID");
                String instagram = resul.getString("Instagram");
                
                AlterarCadastroCentro.setId(id);
                AlterarCadastroCentro.setNomeText(nome);
                AlterarCadastroCentro.setCnpjCentroText(cnpj);
                AlterarCadastroCentro.setEnderecoText(endereco);
                AlterarCadastroCentro.setCelularText(celular);
                AlterarCadastroCentro.setEmailText(emailAutenticado);
                AlterarCadastroCentro.setSenhaText(senha);
                AlterarCadastroCentro.setInstagram(instagram);
                AlterarCadastroCentro.setVisible(true);
                
              
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Email ou Senha inválida");
                
            }
        } 
        catch (SQLException erro) 
        {
            JOptionPane.showMessageDialog(null, "LOGIN" + erro);
        }
        
    }//GEN-LAST:event_BotaoAlterarDadosActionPerformed

    private void BotaoCadastrarPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarPetsActionPerformed
        telaEspeciePet.LimparBox();
        telaEspeciePet.setVisible(true);
        String contato = TxtCelularPerfil.getText();
        String centro = TxtEmailPerfil.getText();
        telaEspeciePet.setcontato(contato);
        telaEspeciePet.setnome(centro);
       
    }//GEN-LAST:event_BotaoCadastrarPetsActionPerformed

    private void TxtNomePerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomePerfilActionPerformed
        
    }//GEN-LAST:event_TxtNomePerfilActionPerformed

    private void TxtCelularPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCelularPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCelularPerfilActionPerformed

    private void TxtEndereçoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEndereçoPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEndereçoPerfilActionPerformed

    private void TxtEmailPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailPerfilActionPerformed
     
    
    }//GEN-LAST:event_TxtEmailPerfilActionPerformed

    private void BotaoExcluirPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirPerfilActionPerformed
            
            int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir a conta?");
            
            
            
            if (resposta == JOptionPane.YES_OPTION) {
            RemoverCentro();
            JOptionPane.showMessageDialog(null, "Centro Removido");
            System.exit(0);
        } else if (resposta == JOptionPane.NO_OPTION) {
            
            JOptionPane.showMessageDialog(null, "Operação cancelada");
        } else {
            
            JOptionPane.showMessageDialog(null, "Operação cancelada");
        }
    }//GEN-LAST:event_BotaoExcluirPerfilActionPerformed

    private void BotaoCadastrarPets1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarPets1ActionPerformed
        ExcluirPets = new ExcluirPets();
        
        
        try 
        {
            String usuario;
        
            usuario = TxtEmailPerfil.getText();
            
            
            centroDeAdoção objcentro = new centroDeAdoção();
            objcentro.setEmail(usuario);
            
            
            CentroAdoçãoBD objDoadorBD = new CentroAdoçãoBD();
            ResultSet resul = objDoadorBD.PedirDadosCentros(objcentro);
            
            
            
            if (resul.next()) 
            {
                
                
                String nome = resul.getString("Email");
                ExcluirPets.setNomeText(nome);
                ExcluirPets.setVisible(true);
                  
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Email ou Senha inválida");
                
            }
        } 
        catch (SQLException erro) 
        {
            JOptionPane.showMessageDialog(null, "LOGIN" + erro);
        }    
        
    }//GEN-LAST:event_BotaoCadastrarPets1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterarDados;
    private javax.swing.JButton BotaoCadastrarPets;
    private javax.swing.JButton BotaoCadastrarPets1;
    private javax.swing.JButton BotaoExcluirPerfil;
    private javax.swing.JButton BotaoSairPerfil;
    private javax.swing.JLabel CnpjPerfil;
    private javax.swing.JLabel NomePerfil;
    private javax.swing.JTextField TxtCelularPerfil;
    private javax.swing.JTextField TxtCnpjPerfil;
    private javax.swing.JTextField TxtEmailPerfil;
    private javax.swing.JTextField TxtEndereçoPerfil;
    private javax.swing.JTextField TxtInstagramPerfil;
    private javax.swing.JTextField TxtNomePerfil;
    private javax.swing.JLabel emailPerfil;
    private javax.swing.JLabel endereçoPerfil;
    private javax.swing.JLabel endereçoPerfil1;
    private javax.swing.JLabel instagramPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

private void RemoverCentro(){
        String sql = "DELETE from centrosdeadocao WHERE NomeFantasia = ?";
        connection = Conexao.getInstance().getConnection();
        PreparedStatement stmt = null;
        try {
            
            stmt = connection.prepareStatement(sql);
            stmt.setString(1, TxtNomePerfil.getText());
            stmt.executeUpdate();
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

}
